plugins {
    id 'com.android.application'
}

android {
    namespace 'com.desarrollamo.storeamo.bootstrap'
    compileSdk 34

    defaultConfig {
        applicationId 'com.desarrollamo.storeamo.installer'
        minSdk 26
        targetSdk 34
        versionCode 6
        versionName '0.0.6'
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
